import Head from "next/head";
import Button from "../components/Button";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import useUser from "../hooks/use-user";

export default function Home() {
  const [user, fetchUser] = useState(null);

  const { data, isLoading } = useUser();
  const songs = user ? user.tracks : data?.tracks;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{user ? "Your" : "Laura's"} Spotify Crushes</h1>
      <Button fetchUser={fetchUser} />
      {isLoading ? (
        "loading..."
      ) : (
        <>
          {songs.map((song, index) => {
            return (
              <article key={song.id}>
                <h2>{song.title}</h2>
                <p>by {song.artist}</p>
              </article>
            );
          })}
        </>
      )}
    </div>
  );
}
